import { chromium } from "playwright";
setTimeout(() => { console.error("timeout"); process.exit(1); }, 120000).unref();
const args = process.argv[2] ? process.argv[2].split("|") : [];
const b = await chromium.launch({ executablePath: "/Users/leoni/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-arm64/chrome-headless-shell", args });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:8081/", { waitUntil: "networkidle" });
await p.waitForTimeout(3000);
console.log(await p.evaluate(() => { const c=document.createElement('canvas'); const g=c.getContext('webgl2')||c.getContext('webgl'); if(!g) return 'no webgl'; const d=g.getExtension('WEBGL_debug_renderer_info'); return d? g.getParameter(d.UNMASKED_RENDERER_WEBGL) : g.getParameter(g.RENDERER); }));
await p.evaluate(() => window.scrollTo(0, 1100));
await p.waitForTimeout(2000);
const r = await p.evaluate(() => new Promise((res) => { let n=0; const t0=performance.now(); const f=()=>{n++; if(performance.now()-t0>6000) res({n,ms:performance.now()-t0}); else requestAnimationFrame(f);}; requestAnimationFrame(f); }));
console.log("fps", (r.n/(r.ms/1000)).toFixed(2));
await b.close();
